# MUVOV Docker Compose 配置 - IPv4 模式
# 适用于大多数部署场景的简化配置

services:
  # Caddy 反向代理和自动 HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: muvov-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ../dist:/srv/muvov
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - peerjs-server
    networks:
      - muvov-network

  # PeerJS 信令服务器
  peerjs-server:
    image: peerjs/peerjs-server
    container_name: muvov-peerjs
    restart: unless-stopped
    command: ["--port", "9000", "--key", "muvov", "--path", "/"]
    expose:
      - "9000"
    networks:
      - muvov-network

  # CoTURN STUN/TURN 服务器
  coturn:
    image: coturn/coturn:latest
    container_name: muvov-coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-65535:49152-65535/udp"
    volumes:
      - ./turnserver-no-tls.conf:/etc/coturn/turnserver.conf
      - caddy_data:/data/caddy:ro  # 只读访问 Caddy 证书
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - muvov-network

volumes:
  caddy_data:
  caddy_config:

networks:
  muvov-network:
    driver: bridge